package options.browse;
import options.post.Post;
import user.User;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * User is the signed in user
 */
public class BrowseUseCase {

    User user;

    public BrowseUseCase(User user) {
        this.user = user;
    }
    /**
     * Generates a feed given the user data given, takes a list that user follows, and takes all of the posts
     * made by these users
     * @param users A Hashmap generated by GetUserDictGateway
     * @param followers a list of usernames that a specific user follows
     * @return A list of posts
     */
    public ArrayList<Post> generateFeed(HashMap<String,Object> users, List<String> followers){
        ArrayList<Post> feed = new ArrayList<>();
        for (String follower : followers) {
            User user1 =(User) users.get(follower);
            feed.addAll(user1.getListPosts());
        }
        return feed;
    }
}
